### ISSUE TITLE
"Memory Usage" README

### ISSUE THREAD

**Issue by ilyaztsv** [RisingStack/example-prometheus-nodejs#2]
Hello!

README contains the following:

> Average Memory Usage
> In Megabyte.
> 
> avg(nodejs_external_memory_bytes / 1024) by (service)

but **nodejs_external_memory_bytes** is size in bytes, therefore, we need use `avg(nodejs_external_memory_bytes / 1024 / 1024)` in order to show size in megabytes?

**Comment by Shadowbeetle** [comment]
Thanks! Fixed it.
