### ISSUE TITLE
grafana dashboard memory calculation is only divided by 1024

### ISSUE THREAD

**Issue by yohay-ma** [RisingStack/example-prometheus-nodejs#7]
thanks for this example!

https://github.com/RisingStack/example-prometheus-nodejs/blob/c042e0c2fd736005bcfcda183cd1857fd9704b0c/grafana-dashboard.json#L439

Why the memory calculation is only divided by 1024?
`avg(nodejs_external_memory_bytes / 1024 ) by (service)`
isn't it suppose to be:
`avg(nodejs_external_memory_bytes / 1024 / 1024 ) by (service)`

**Comment by Shadowbeetle** [comment]
I'm glad it helped! 

In our example, MB was better as we wanted finer grained info. GB are preferable if you have a lot of it and make the graph more readable. With small, 1 GB VMs it's an overkill. 

It depends on your preference and available memory.

**Comment by yohay-ma** [comment]
thanks
